// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Registration.Persistence.DbContext;

#nullable disable

namespace Registration.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250811052334_MakeRoleIdManual")]
    partial class MakeRoleIdManual
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Registration.Domain.Entities.Role", b =>
                {
                    b.Property<int>("Role_Id")
                        .HasColumnType("integer");

                    b.Property<string>("Project_Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role_Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Role_Id");

                    b.HasIndex("Role_Id")
                        .IsUnique();

                    b.ToTable("Roles");
                });
#pragma warning restore 612, 618
        }
    }
}
